--- #YAML:1.0
name:               CopyTree-VendorProof-LocalFileOp
version:            0.0011
abstract:           Perl extension for providing a connecter instance for CopyTree::VendorProof.
author:
    - dbmolester de gmail.com
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:                 0
    CopyTree::VendorProof:  0.0011
    Data::Dumper:         0
    File::Basename:       0
    MIME::Base64:         0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
